---
controller_organizations:
  - name: "virtualization"
    description: "Virtualization Team"
    state: present
    galaxy_credentials:
      - ah_published
      - ah_certified
      - ah_community

controller_credentials:
  - name: "ocp-api-token"
    description: "OpenShift API Bearer Token"
    organization: "virtualization"
    credential_type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ ocp_host }}"
      verify_ssl: false
      bearer_token: "{{ ocp_token }}"
# type might be kubernetes_bearer_token
  - name: "access-virt-vms-cred"
    description: "Credential to access OpenShift Virtualization VMs via ssh"
    organization: "virtualization"
    credential_type: "Machine"
    inputs:
      username: "fedora"
      password: "fedora"

controller_projects:
  - name: "ocpvirt-project"
    description: "Virtualization Demo"
    organization: "virtualization"
    scm_type: git
    scm_url: "https://github.com/derekwaters/ansible_devops_demo.git"
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: true
    update_project: true
    wait: true
    state: present
  - name: "ocpvirt-inventory"
    description: "OpenShift Virtualization Inventory Source"
    organization: "virtualization"
    scm_type: git
    scm_url: "https://github.com/derekwaters/ansible_inventory_sources.git"
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: true
    update_project: true
    wait: true
    state: present

controller_inventories:
  - name: "ocpvirt-vms"
    description: "OpenShift Virtualization Virtual Machines"
    organization: "virtualization"
    state: present

controller_inventory_sources:
  - name: "ocpvirt-vms-source"
    source: "scm"
    inventory: "ocpvirt-vms"
    organization: "virtualization"
    source_project: "ocpvirt-inventory"
    credential: "ocp-api-token"
    verbosity: 2
    overwrite: true
    state: present

controller_execution_environments:
  - name: "infra-ee"
    description: "Execution Environment including infra collections"
    organization: "virtualization"
    image: "quay.io/rh-ee-dwaters/infra-ee"
    state: present

controller_templates:
  - name: "patch-vms"
    playbook: "demo_virt_eda/playbooks/patch-vms.yml"
    job_type: "run"
    organization: "virtualization"
    inventory: "ocpvirt-vms"
    project: "ocpvirt-project"
    ask_variables_on_launch: true
    credentials:
      - "access-virt-vms-cred"
    state: present

  - name: "add-vm-to-inventory"
    playbook: "demo_virt_eda/playbooks/add-vm-to-inventory.yml"
    job_type: "run"
    organization: "virtualization"
    inventory: "Demo Inventory"
    project: "ocpvirt-project"
    execution_environment: "infra-ee"
    ask_variables_on_launch: true
    limit: "namespace_{{ vmnamespace |replace('-', '_') }}"
    extra_vars:
      controller_hostname: "{{ controller_hostname }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
    credentials:
      - "Demo Credential"
    state: present

controller_workflows:
  - name: "add-vm-and-patch"
    description: "Add a new OCPVirt VM to the CMDB inventory and apply patches"
    organization: "virtualization"
    inventory: "Demo Inventory"
    state: present
    ask_variables_on_launch: true
    simplified_workflow_nodes:
      - identifier: add-vm
        unified_job_template: "add-vm-to-inventory"
        success_nodes:
          - "patch-vms"
        failure_nodes: []
        always_nodes: []
        credentials: []

      - identifier: patch-vms
        unified_job_template: "patch-vms"
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
...
